### ISSUE TITLE
Apotheosis causes softlocks on the server thread

### ISSUE THREAD

**Issue by rinOfTheStars** [Wizelf402/Permafrost#11]
see https://github.com/Shadows-of-Fire/Apotheosis/issues/395

**Comment by rinOfTheStars** [comment]
Likely caused by two things:
1. Malformated item configs
2. Mobs that are not derived from `MobEntity` (this probably shouldn't happen unless a mod is poorly coded anyways)

**Comment by rinOfTheStars** [comment]
also see https://github.com/Shadows-of-Fire/Apotheosis/issues/396, alongside https://github.com/cocona20xx/Apotheosis

**Comment by NevadaActual** [comment]
As this issue was created before 1.1.6 I'm going to close it, as that version resolves many of the Apotheosis related crashes and bugs. If you have similar issues post 1.1.6, please create a new issue.

(We're overhauling the repo, due to updates before release 1.2 being extremely unstable. Give us a day or two, and we'll have bug templates ready for use.)

**Comment by NevadaActual** [comment]
Annnnd reports are coming back of the issue remaining. Reopening the issue.

**Comment by rinOfTheStars** [comment]
Likely due to a file getting reverted during the move from 1.1.6pre1 to 1.1.6
man, we really need a proper buildchain aeugh
going to get the 1.1.6 files on the main branch and do a comparison

**Comment by rinOfTheStars** [comment]
Possibly fixed with 3457824? Need someone to verify that!

**Comment by NevadaActual** [comment]
With the release of 1.2, these crashes should be resolved! Closing this issue, barring further crashes appearing.
