### ISSUE TITLE
Hardcore Quest mod crash on placing runic altar

### ISSUE THREAD

**Issue by Spaig** [Wizelf402/Permafrost#26]
Just as it says: whenever someone places a runic altar, their client crashes. Server seems unaffected, nothing in server logs.  We had three different people try it with three separate altars. Client crash log here:

https://pastebin.com/PiM8P1MJ

Server running server pack 1.2, client running client 1.2 via GDLauncher.

**Comment by rinOfTheStars** [comment]
Likely due to block placement quests being broken clientside? This probably needs a quest fix of some sort than to patch around that until its fixed. My suspicion is that the quest complete render popup breaks for some reason under this specific edge case? Probably needs to be reported to both mod issue trackers if so.

**Comment by rinOfTheStars** [comment]
Might also just be that block placement quests are totally broken

**Comment by rinOfTheStars** [comment]
Will be fixed with an upcoming update.
