### ISSUE TITLE
Intermittant connectivity issue to server

### ISSUE THREAD

**Issue by pyrebuilder** [Wizelf402/Permafrost#51]
Hello, this is a shot in the dark, but I am hoping someone will know how to help.
My friend and I are in the same house, with the server also in the same network, everything testing 40mbps+ between wirelessly connected computers.
Last week we were both able to play, but now when she tries to connect, the gets stuck on "Encrypting" and then is disconnected. The log says:
`[24Aug2021 16:29:42.940] [User Authenticator #3/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player NAME is NUMBER
[24Aug2021 16:30:12.473] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: Disconnecting com.mojang.authlib.GameProfile@NUMBER[id=NUMBER,name=NAME,properties={textures=[com.mojang.authlib.properties.Property@NUMBER]},legacy=false] (/10.0.0.34:54312): Took too long to log in
[24Aug2021 16:30:12.523] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: Disconnecting com.mojang.authlib.GameProfile@NUMBER[id=NUMBER,name=NAME,properties={textures=[com.mojang.authlib.properties.Property@NUMBER]},legacy=false] (/10.0.0.34:54312): Took too long to log in
`
I've replaced all user specific UUID and names with NAME and NUMBER of course.

The port number after the local IP (10.0.0.34) is different each time she attempts to log in, I've seen at least a dozen different ports in that spot, and I've tried a gambit of troubleshooting. Direct ethernet connection, turn off firewalls, check port forwarding is working, end all background processes on her laptop, try a different launcher, and I've been troubleshooting this for roughly 8 hours now.

We are both still playing on version 2.0 and I got the server working on 2.0, and we've been playing happily for months until this started happening. Does anyone know why or could you offer any help? (We are planning on finishing our playthrough on 2.0 before moving to the newer versions, as it might dramatically change gameplay)

Thank you.

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.
