### ISSUE TITLE
Quest False Fire slingshot detection task bugged: the slingshot is not being detected by the quest book

### ISSUE THREAD

**Issue by RickLeDoge** [Wizelf402/Permafrost#52]
I tried manual detection but it didn't work either

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.
