### ISSUE TITLE
server looping after restart

### ISSUE THREAD

**Issue by jammer131** [Wizelf402/Permafrost#55]
seems the server files are having issues with an infinite loop after restarting it. had to completely reinstall the files to fix it.

https://pastebin.com/dzc0z9XN

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.
