### ISSUE TITLE
Incomplete set of tags received from server

### ISSUE THREAD

**Issue by RyanSecrest** [Wizelf402/Permafrost#60]
I downloaded the 5.0.1 server download and it says this everytime. I tried changing the forge.jar to server.jar if that does anything.

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.
