### ISSUE TITLE
Consecration quest

### ISSUE THREAD

**Issue by martingolding96** [Wizelf402/Permafrost#61]
The consecration quest hasn't detected me crafting the fire stick. I am on version 5.1.1

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.
