### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by DieselDorky16** [Wizelf402/Permafrost#63]
Game crashed: The game crashed whilst initializing game
Error: java.lang.IllegalStateException: GLFW error before init: [0x10008]Cocoa: Failed to find service port for display
Exit Code: 255

[latest.log](https://github.com/Wizelf402/Permafrost/files/7824826/latest.log)

**Comment by NevadaActual** [comment]
As I haven't been maintaining the Github for quite some time, I'm wiping all open issues with the same message:

Please comment on this issue OR make a new one if this issue remains relevant for you. It makes it simpler for me to close all of these issues that may or may not have people checking on them, and letting them come back instead of me spending time trying to track them down, as I can better spend that time and energy working on the modpack. Thank you for your time, I will be very willing to help you in the coming weeks.

**Comment by MonfGeiger** [comment]
well, in that case, i will reuse this issue ticket and reopen it. I discovered this modpack from (i kid you not) a fanfic story on fanficton.net, so i decided to download it via the FTB App and use MultiMC to import it over (im more of an AIO (All In One) type person instead of 3+ launchers for different and/or launcher exclusive modpacks). Thing is, it only gort the config folder, so o did the good ol copy/paste and rechecked the instance settings to make sure everything was kosher, ran it, and it crashed.

I later found out from the MultiMC support team that the forge version its running (36.2.23) doesnt like java 8u351 which i use as default, so i grabbed an archived .zip zulu build of 8u312 and it runs fine. I wanted some further clarification: was this modpack always meant to run off a specific forge & java version, or could i bump up the forge number and keep my 8u351 instead? I already have 3 java's installed (8u351, jdk 17, and jdk19), adding a fourth feels a bit excessive
