### ISSUE TITLE
CT scripts have broken

### ISSUE THREAD

**Issue by thePalindrome** [Wizelf402/Permafrost#65]
https://mclo.gs/BksCm8m

Log link included for further reference, but a few things I've noted:

"Pyromancy" is now called "pyromancer", which is already breaking a good number of scripts. This seems to have culminated to even things like fire charges no longer having the correct recipe.

Apologies I can't be more help, but I'm not familiar with the ecosystem around 1.16

**Comment by NevadaActual** [comment]
I'm looking into this now. Give me a short while to check over things.

**Comment by NevadaActual** [comment]
It appears that you are missing "Better End Forge" entirely? Due to how Craft Tweaker works, any error at all causes everything loading after that to break, and since Better End Forge has recipes edited erroring due to those recipes *not existing*, it burns all scripts after that edit.

Error in question causing your issues: "[12:26:22] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [ERROR] Parser Exception @ Survival/alternatives.zs:43:42 : Invalid parameters to BEP block: '<block:betterendforge:dense_emerald_ice>. There may be more information about this in the log.: Survival/alternatives.zs:43:42: Invalid parameters to BEP block: '<block:betterendforge:dense_emerald_ice>. There may be more information about this in the log.

[12:26:22] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [ERROR] Scripts are invalid!"

Please fresh reinstall the pack, and the serverpack if it's being used, and tell me if the problem persists. 

(As far as I can tell, pyromancer recipes weren't erroring out? But if it continues happening after a fresh install *with* Better End Forge installed, then I can look more deeply at the issue using your logs. In the meantime, my fresh local copy is without errors, so I can't really simulate your issues without serious guesswork. If you're willing/free, I can also sit down with you on Discord to try working through this with you personally. What time zone are you in, so I can try to plan around being awake when you are as well?)

**Comment by thePalindrome** [comment]
Oh wow, surprisingly that one fix fixed everything.
I do apologize for missing things. Since the CF launcher hasn't been available for my platform, I was using PolyMC, and must have missed it in the list of mods that it was blocked from accessing.

The `pyromancy:` entries must've been a red herring, although hopefully you can understand why it drew my eye, since it seemed to be a change in the modid. In the event you want to follow up on discord, my discriminator is #8270

I apologize again for having raised an issue over such a simple mistake.
